### ISSUE TITLE
URL validator

### ISSUE THREAD

**Issue by kelunik** [thephpleague/uri-whatwg#1]
## Issue summary

Given the upcoming changes to https://github.com/thephpleague/uri-parser, which will make it more permissive regarding hosts as defined in the corresponding RFC, there should maybe be a separate package doing validations according to https://url.spec.whatwg.org/, which are specific to URLs, not generic URIs.

I don't have any specific plans, just opening this as a reminder.

**Comment by nyamsprod** [comment]
@kelunik during my search for alternative implementation of the WHATWG URL parser I stumble on this package https://github.com/TRowbotham/URL-Parser  which essentially does what you want 👍 . So instead of re-inventing the wheel I've started submitting PR to the package and the maintainer was kind enough to accept them. So I'll definetly close this repo since it is no longer needed and I will instead try to see if I can help the other package in fixing bug or else.
